""" Adds photos table

Revision ID: 24c7c6615e33
Revises: 9cd0959e1465
Create Date: 2023-05-29 11:04:11.470785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24c7c6615e33'
down_revision = '9cd0959e1465'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('photo_id', postgresql.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
    sa.Column('report_id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.report_id'], ),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.create_index(op.f('ix_photos_is_active'), 'photos', ['is_active'], unique=False)
    op.add_column('addresses', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    op.execute(
        """
            CREATE TRIGGER set_timestamp
                BEFORE UPDATE ON photos
                FOR EACH ROW
                EXECUTE PROCEDURE trigger_set_timestamp();
        """
    )

    op.execute(
        """
            CREATE OR REPLACE TRIGGER trigger_update_is_active_photos
                after UPDATE OF is_active ON reports
                EXECUTE PROCEDURE update_is_active('photos', 'report_id', 'report_id');
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'number')
    op.drop_index(op.f('ix_photos_is_active'), table_name='photos')
    op.drop_table('photos')
    # ### end Alembic commands ###

    op.execute("DROP TRIGGER set_timestamp ON photos;")
    op.execute("DROP TRIGGER trigger_update_is_active_photos ON reports;")
